services:
  # --- BACKEND (Go) ---
  backend:
    build: ./backend
    container_name: jl_backend
    env_file:
      - ./backend/.env
    ports:
      - ${PUERTO_BACKEND}
    networks:
      - app-network

  # --- FRONTEND (React/Vite) ---
  frontend:
    build: ./frontend
    container_name: jl_frontend
    env_file:
      - ./frontend/.env
    depends_on:
      - backend
    networks:
      - app-network
    ports:
      - ${PUERTO_FRONTEND}
  
  # --- WATCH TOWER ---
  watchtower:
    image: containrrr/watchtower
    container_name: jl_watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_CLEANUP=true
      - DOCKER_HUB_USERNAME=${DOCKER_HUB_USERNAME}
      - DOCKER_HUB_PASSWORD=${DOCKER_HUB_ACCESS_TOKEN}
    command: --interval 300 

networks:
  app-network:

