version: "3.7"

services:
  # --- BACKEND (Go) ---
  backend:
    build: ./backend
    container_name: jl_backend
    env_file:
      - ./backend/.env
    ports:
      - "1000:1000"
    depends_on:
      - db
    networks:
      - app-network

  # --- FRONTEND (React/Vite) ---
  frontend:
    build: ./frontend
    container_name: jl_frontend
    env_file:
      - ./frontend/.env
    depends_on:
      - backend
    networks:
      - app-network
    ports:
      - "3000:80" # El puerto 80 dentro del contenedor se mapea al puerto 3000 en el host

  # --- DATABASE (PostgreSQL) ---
  db:
    image: postgres:15
    container_name: jl_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1020
      POSTGRES_DB: naruto
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./backend/ddl.sql:/docker-entrypoint-initdb.d/ddl.sql
    ports:
      - "5432:5432"
    networks:
      - app-network

  # --- NGINX Reverse Proxy (sin SSL) ---
  nginx:
    image: nginx:alpine # Usamos la imagen oficial de Nginx
    container_name: jl_nginx
    depends_on:
      - frontend
      - backend
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d # Volumen para la configuración de Nginx
    ports:
      - "8081:80" # Solo HTTP, no SSL
    networks:
      - app-network
  # --- CERTBOT (SSL) --- (No se utiliza en este caso, ya que no queremos SSL)
  # No es necesario en este caso, puedes omitirlo.

networks:
  app-network:


volumes:
  pg_data:
